# === Spotify API Credentials ===
# Get yours at: https://developer.spotify.com/dashboard
SPOTIPY_CLIENT_ID = 'YOUR_CLIENT_ID_HERE'
SPOTIPY_CLIENT_SECRET = 'YOUR_CLIENT_SECRET_HERE'
SPOTIPY_REDIRECT_URI = 'http://127.0.0.1:8888/callback'

# === Gesture Control Settings ===
WEBCAM_INDEX = 0
GESTURE_THRESHOLD = 0.7
VOLUME_SENSITIVITY = 0.05
MOUSE_SENSITIVITY = 1.5
MIN_DETECTION_CONFIDENCE = 0.5
MIN_TRACKING_CONFIDENCE = 0.5
MODEL_COMPLEXITY = 0
FRAME_WIDTH = 640
FRAME_HEIGHT = 480

# === Advanced Optimization ===
SMOOTHING_FACTOR = 0.65
ROTATION_THRESHOLD = 0.0005
GESTURE_COOLDOWN = 0.5
